spring:
  application:
    name: coordi

  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs/json
  swagger-ui:
    enabled: true
    path: /api-docs.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json